# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end
@porter = Family.create!(name: "Porter")
@finder = Family.create!(name: "Finder")
@lines = Family.create!(name: "Lines")
@burnett = Family.create!(name: "Burnett")
@pini = Family.create!(name: "Pini")
@jones = Family.create!(name: "Jones")
@saechao = Family.create!(name: "Saechao")
@gillespie = Family.create!(name: "Gillespie")
@taylor = Family.create!(name: "Taylor")
@schnepf = Family.create!(name: "Schnepf")
@edmunds = Family.create!(name: "Edmunds")

@marlane = Descendent.create(first_name: "Marlane", family_id: @porter.id, female: true, languages_spoken: 1)
@don = Descendent.create(first_name: "Don", family_id: @porter.id, female: false, languages_spoken: 2)

@marlane_and_don = Relationship.create(mom_id: @marlane.id, dad_id: @don.id)

@aaron = Descendent.create(first_name: "Aaron", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @marlane_and_don.id)
@stacee = Descendent.create(first_name: "Stacee", family_id: @porter.id, female: true, languages_spoken: 1)
@amy = Descendent.create(first_name: "Amy", family_id: @finder.id, female: true, languages_spoken: 1, parents_id: @marlane_and_don.id)
@rich = Descendent.create(first_name: "Rich", family_id: @finder.id, female: false, languages_spoken: 1)
@alissa = Descendent.create(first_name: "Alissa", family_id: @lines.id, female: true, languages_spoken: 1, parents_id: @marlane_and_don.id)
@joe = Descendent.create(first_name: "Joe", family_id: @lines.id, female: false, languages_spoken: 1)
@dana = Descendent.create(first_name: "Dana", family_id: @burnett.id, female: true, languages_spoken: 2, parents_id: @marlane_and_don.id)
@travis = Descendent.create(first_name: "Travis", family_id: @burnett.id, female: false, languages_spoken: 1)
@justin = Descendent.create(first_name: "Justin", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @marlane_and_don.id)
@brittney = Descendent.create(first_name: "Brittney", family_id: @porter.id, female: true, languages_spoken: 1)
@lee = Descendent.create(first_name: "Lee", family_id: @porter.id, female: false, languages_spoken: 2, parents_id: @marlane_and_don.id)
@amanda = Descendent.create(first_name: "Amanda", family_id: @porter.id, female: true, languages_spoken: 1)
@rusty = Descendent.create(first_name: "Rusty", family_id: @porter.id, female: false, languages_spoken: 3, parents_id: @marlane_and_don.id)
@yain = Descendent.create(first_name: "Yain", family_id: @porter.id, female: true, languages_spoken: 3)

@stacee_and_aaron = Relationship.create(mom_id: @stacee.id, dad_id: @aaron.id)
@amy_and_rich = Relationship.create(mom_id: @amy.id, dad_id: @rich.id, married: false)
@alissa_and_joe = Relationship.create(mom_id: @alissa.id, dad_id: @joe.id)
@dana_and_travis = Relationship.create(mom_id: @dana.id, dad_id: @travis.id)
@brittney_and_justin = Relationship.create(mom_id: @brittney.id, dad_id: @justin.id)
@amanda_and_lee = Relationship.create(mom_id: @amanda.id, dad_id: @lee.id)
@yain_and_rusty = Relationship.create(mom_id: @yain.id, dad_id: @rusty.id)

@morgan = Descendent.create(first_name: "Morgan", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @stacee_and_aaron.id)
@rayden = Descendent.create(first_name: "Rayden", family_id: @porter.id, female: false, languages_spoken: 2, parents_id: @stacee_and_aaron.id)
@rylee = Descendent.create(first_name: "Rylee", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @stacee_and_aaron.id)
@saydi = Descendent.create(first_name: "Saydi", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @stacee_and_aaron.id)
@halee = Descendent.create(first_name: "Halee", family_id: @porter.id, female: true, languages_spoken: 2, parents_id: @stacee_and_aaron.id)
@brett = Descendent.create(first_name: "Brett", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @stacee_and_aaron.id)
@logan = Descendent.create(first_name: "Logan", family_id: @porter.id, female: false, languages_spoken: 2, parents_id: @stacee_and_aaron.id)
@hana = Descendent.create(first_name: "Hana", family_id: @finder.id, female: true, languages_spoken: 1, parents_id: @amy_and_rich.id)
@ethan = Descendent.create(first_name: "Ethan", family_id: @finder.id, female: false, languages_spoken: 1, parents_id: @amy_and_rich.id)
@oran = Descendent.create(first_name: "Oran", family_id: @finder.id, female: false, languages_spoken: 1, parents_id: @amy_and_rich.id)
@kael = Descendent.create(first_name: "Kael", family_id: @finder.id, female: false, languages_spoken: 1, parents_id: @amy_and_rich.id)
@jaci = Descendent.create(first_name: "Jaci", family_id: @gillespie.id, female: true, parents_id: @alissa_and_joe.id)
@cameron = Descendent.create(first_name: "Cameron", family_id: @gillespie.id, female: false, languages_spoken: 1)
@cami = Descendent.create(first_name: "Cami", family_id: @lines.id, female: true, parents_id: @alissa_and_joe.id)
@brian = Descendent.create(first_name: "Brian", family_id: @lines.id, female: false, languages_spoken: 2, parents_id: @alissa_and_joe.id)
@allen = Descendent.create(first_name: "Allen", family_id: @lines.id, female: false, parents_id: @alissa_and_joe.id)
@caroyln = Descendent.create(first_name: "Carolyn", family_id: @lines.id, female: true, parents_id: @alissa_and_joe.id)
@robert = Descendent.create(first_name: "Robert", family_id: @lines.id, female: false, parents_id: @alissa_and_joe.id)
@tj = Descendent.create(first_name: "TJ", family_id: @burnett.id, female: false, languages_spoken: 1, parents_id: @dana_and_travis.id)
@natalie = Descendent.create(first_name: "Natalie", family_id: @taylor.id, female: true, languages_spoken: 1, parents_id: @dana_and_travis.id)
@matthew = Descendent.create(first_name: "Matthew", family_id: @taylor.id, female: false, languages_spoken: 1)
@elaina = Descendent.create(first_name: "Elaina", family_id: @burnett.id, female: true, languages_spoken: 1, parents_id: @dana_and_travis.id)
@tyler = Descendent.create(first_name: "Tyler", family_id: @burnett.id, female: false, languages_spoken: 1, parents_id: @dana_and_travis.id)
@lydia = Descendent.create(first_name: "Lydia", family_id: @burnett.id, female: true, languages_spoken: 1, parents_id: @dana_and_travis.id)
@zander = Descendent.create(first_name: "Zander", family_id: @burnett.id, female: false, languages_spoken: 1, parents_id: @dana_and_travis.id)
@maddie = Descendent.create(first_name: "Maddie", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @brittney_and_justin.id)
@mckinlee = Descendent.create(first_name: "McKinlee", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @brittney_and_justin.id)
@monroe = Descendent.create(first_name: "Monroe", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @brittney_and_justin.id)
@millie = Descendent.create(first_name: "Millie", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @brittney_and_justin.id)
@eden = Descendent.create(first_name: "Eden", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @amanda_and_lee.id)
@delia = Descendent.create(first_name: "Delia", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @amanda_and_lee.id)
@gwen = Descendent.create(first_name: "Gwen", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @amanda_and_lee.id)
@emerson = Descendent.create(first_name: "Emerson", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @amanda_and_lee.id)
@adeline = Descendent.create(first_name: "Adeline", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @yain_and_rusty.id)
@brielle = Descendent.create(first_name: "Brielle", family_id: @porter.id, female: true, languages_spoken: 1, parents_id: @yain_and_rusty.id)
@callum = Descendent.create(first_name: "Callum", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @yain_and_rusty.id)

@saydi_and_rylee = Relationship.create(mom_id: @saydi.id, dad_id: @rylee.id)

@elliot = Descendent.create(first_name: "Elliot", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @saydi_and_rylee.id)
@noah = Descendent.create(first_name: "Noah", family_id: @porter.id, female: false, languages_spoken: 1, parents_id: @saydi_and_rylee.id)

@jaci_and_cameron = Relationship.create(mom_id: @jaci.id, dad_id: @cameron.id)

@graham = Descendent.create(first_name: "Graham", family_id: @gillespie.id, female: false, languages_spoken: 1, parents_id: @jaci_and_cameron.id)

@natalie_and_matthew = Relationship.create(mom_id: @natalie.id, dad_id: @matthew.id)

@peyton = Descendent.create(first_name: "Peyton", family_id: @taylor.id, female: true, languages_spoken: 1, parents_id: @natalie_and_matthew.id)
@tatum = Descendent.create(first_name: "Tatum", family_id: @taylor.id, female: true, languages_spoken: 1, parents_id: @natalie_and_matthew.id)


# @rome= @rusty.missions.create(mission_name:"Rome", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
# @pennsylvania = @aaron.missions.create(mission_name: "Pennyslvania", mission_language: "English", country: "United States", members_baptized: 10, foreign_mission: false)
# @oaklahoma = @justin.missions.create(mission_name:"Tulsa", mission_language: "English", country: "United States", members_baptized: 5, foreign_mission: false)
# @brazil = @lee.missions.create(mission_name:"Riberão Preto", mission_language: "Portugese", country: "Brazil", members_baptized: 7, foreign_mission: true)
# @spain = @aaron.missions.create(mission_name:"Madrid", mission_language: "Spanish", country: "Spain", members_baptized: 11, foreign_mission: true)
# @japan = @rayden.missions.create(mission_name: "Tokyo", mission_language: "Japanese", country: "Japan", members_baptized: 3, foreign_mission: true)
# @tennessee = @rylee.missions.create(mission_name: "Tenessee", mission_language: "English", country: "United States", members_baptized: 3, foreign_mission: false)
# @milan= @halee.missions.create(mission_name:"Milan", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
# @gilbert = @brett.missions.create(mission_name: "Gilbert", mission_language: "English", country: "United States", members_baptized: 0, foreign_mission: false)
# @asuncion = @logan.missions.create(mission_name:"Asuncion", mission_language: "Spanish", country: "Paraguay", members_baptized: 4, foreign_mission: true)
# @puebla = @elaina.missions.create(mission_name:"Puebla", mission_language: "Spanish", country: "Mexico", members_baptized: 4, foreign_mission: true)
# @tijuana = @brian.missions.create(mission_name:"Tijuana", mission_language: "Spanish", country: "Mexico", members_baptized: 4, foreign_mission: true)
# @anchorage = @allen.missions.create(mission_name:"Anchorage", mission_language: "English", country: "United States", members_baptized: 4, foreign_mission: false)
