# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

@porters = Surname.create!(last_name: "Porter")
@finders = Surname.create!(last_name: "Finders")
@lines = Surname.create!(last_name: "Lines")
@burnett = Surname.create!(last_name: "Burnett")
@pini = Surname.create!(last_name: "Pini")
@jones = Surname.create!(last_name: "Jones")
@saechao = Surname.create!(last_name: "Saechao")
@gillespie = Surname.create!(last_name: "Gillespie")
@taylor = Surname.create!(last_name: "Taylor")
@schnepf = Surname.create!(last_name: "Schnepf")
@edmunds = Surname.create!(last_name: "Edmunds")

@marlane = Person.create(first_name: "Marlane", surname_id: 1, female: true, languages_spoken: 1)
@don = Person.create(first_name: "Don", surname_id: 1, female: false, languages_spoken: 2)

@marlane_and_don = Parent.create(mother_id: @marlane.id, father_id: @don.id, married: true)

@aaron = Person.create(first_name: "Aaron", surname_id: 1, female: false, parents_id:1, languages_spoken: 1)
@stacee = Person.create(first_name: "Stacee", surname_id: 1, female: true, parents_id:1, languages_spoken: 1)
@amy = Person.create(first_name: "Amy", surname_id: 2, female: true, parents_id:1, languages_spoken: 1)
@rich = Person.create(first_name: "Rich", surname_id: 1, female: false, languages_spoken: 1)
@alissa = Person.create(first_name: "Alissa", surname_id: 3, female: true, parents_id:1, languages_spoken: 1)
@joe = Person.create(first_name: "Joe", surname_id: 3, female: false, languages_spoken: 1)
@dana = Person.create(first_name: "Dana", surname_id: 4, female: true, languages_spoken: 2)
@travis = Person.create(first_name: "Travis", surname_id: 4, female: false, languages_spoken: 1)
@justin = Person.create(first_name: "Justin", surname_id: 1, female: false, parents_id:1, languages_spoken: 1)
@brittney = Person.create(first_name: "Brittney", surname_id: 1, female: true, languages_spoken: 1)
@lee = Person.create(first_name: "Lee", surname_id: 1, female: false, languages_spoken: 2)
@amanda = Person.create(first_name: "Amanda", surname_id: 1, female: true, languages_spoken: 1)
@rusty = Person.create(first_name: "Rusty", surname_id: 1, female: false, parents_id: 1, languages_spoken: 3)
@yain = Person.create(first_name: "Yain", surname_id: 1, female: true, languages_spoken: 3)

@stacee_and_aaron = Parent.create(mother_id: @stacee.id, father_id: @aaron.id, married: true)
@amy_and_rich = Parent.create(mother_id: @amy.id, father_id: @rich.id, married: false)
@alissa_and_joe = Parent.create(mother_id: @alissa.id, father_id: @joe.id, married: true)
@dana_and_travis = Parent.create(mother_id: @dana.id, father_id: @travis.id, married: true)
@brittney_and_justin = Parent.create(mother_id: @brittney.id, father_id: @justin.id, married: true)
@amanda_and_lee = Parent.create(mother_id: @amanda.id, father_id: @lee.id, married: true)
@yain_and_rusty = Parent.create(mother_id: @yain.id, father_id: @rusty.id, married: true)

@morgan = Person.create(first_name: "Morgan", surname_id: 1, female: true, parents_id:2, languages_spoken: 1)
@rayden = Person.create(first_name: "Rayden", surname_id: 1, female: false, parents_id:2, languages_spoken: 2)
@rylee = Person.create(first_name: "Rylee", surname_id: 1, female: false, parents_id:2, languages_spoken: 1)
@saydi = Person.create(first_name: "Saydi", surname_id: 1, female: true, languages_spoken: 1)
@halee = Person.create(first_name: "Halee", surname_id: 1, female: true, parents_id:2, languages_spoken: 2)
@brett = Person.create(first_name: "Brett", surname_id: 1, female: false, parents_id:2, languages_spoken: 1)
@logan = Person.create(first_name: "Logan", surname_id: 1, female: false, parents_id:2, languages_spoken: 2)
@hana = Person.create(first_name: "Hana", surname_id: 2, female: true, parents_id:3, languages_spoken: 1)
@ethan = Person.create(first_name: "Ethan", surname_id: 2, female: false, parents_id:3, languages_spoken: 1)
@oran = Person.create(first_name: "Oran", surname_id: 2, female: false, parents_id:3, languages_spoken: 1)
@kael = Person.create(first_name: "Kael", surname_id: 2, female: false, parents_id:3, languages_spoken: 1)
@jaci = Person.create(first_name: "Jaci", surname_id: 8, female: true, parents_id:4, languages_spoken: 1)
@cameron = Person.create(first_name: "Cameron", surname_id: 8, female: false, languages_spoken: 1)
@cami = Person.create(first_name: "Cami", surname_id: 3, female: true, parents_id:4, languages_spoken: 1)
@brian = Person.create(first_name: "Brian", surname_id: 3, female: false, parents_id:4, languages_spoken: 2)
@allen = Person.create(first_name: "Allen", surname_id: 3, female: false, parents_id:4, languages_spoken: 1)
@caroyln = Person.create(first_name: "Carolyn", surname_id: 3, female: true, parents_id:4, languages_spoken: 1)
@robert = Person.create(first_name: "Robert", surname_id: 3, female: false, parents_id:4, languages_spoken: 1)
@tj = Person.create(first_name: "TJ", surname_id: 4, female: false, parents_id:5, languages_spoken: 1)
@natalie = Person.create(first_name: "Natalie", surname_id: 9, female: true, parents_id:5, languages_spoken: 1)
@matthew = Person.create(first_name: "Matthew", surname_id: 9, female: false, languages_spoken: 1)
@elaina = Person.create(first_name: "Elaina", surname_id: 4, female: true, parents_id:5, languages_spoken: 1)
@tyler = Person.create(first_name: "Tyler", surname_id: 4, female: false, parents_id:5, languages_spoken: 1)
@lydia = Person.create(first_name: "Lydia", surname_id: 4, female: true, parents_id:5, languages_spoken: 1)
@zander = Person.create(first_name: "Zander", surname_id: 4, female: false, parents_id:5, languages_spoken: 1)
@maddie = Person.create(first_name: "Maddie", surname_id: 1, female: true, parents_id:6, languages_spoken: 1)
@mckinlee = Person.create(first_name: "McKinlee", surname_id: 1, female: true, parents_id:6, languages_spoken: 1)
@monroe = Person.create(first_name: "Monroe", surname_id: 1, female: true, parents_id:6, languages_spoken: 1)
@millie = Person.create(first_name: "Millie", surname_id: 1, female: true, parents_id:6, languages_spoken: 1)
@eden = Person.create(first_name: "Eden", surname_id: 1, female: true, parents_id:7, languages_spoken: 1)
@delia = Person.create(first_name: "Delia", surname_id: 1, female: true, parents_id:7, languages_spoken: 1)
@gwen = Person.create(first_name: "Gwen", surname_id: 1, female: true, parents_id:7, languages_spoken: 1)
@emerson = Person.create(first_name: "Emerson", surname_id: 1, female: false, parents_id:7, languages_spoken: 1)
@adeline = Person.create(first_name: "Adeline", surname_id: 1, female: true, parents_id:8, languages_spoken: 1)
@brielle = Person.create(first_name: "Brielle", surname_id: 1, female: true, parents_id:8, languages_spoken: 1)
@callum = Person.create(first_name: "Callum", surname_id: 1, female: false, parents_id:8, languages_spoken: 1)

@saydi_and_rylee = Parent.create(mother_id: @saydi.id, father_id: @rylee.id, married: true)

@elliot = Person.create(first_name: "Elliot", surname_id: 1, female: false, parents_id:9, languages_spoken: 1)
@noah = Person.create(first_name: "Noah", surname_id: 1, female: false, parents_id:9, languages_spoken: 1)

@jaci_and_cameron = Parent.create(mother_id: @jaci.id, father_id: @cameron.id, married: true)

@graham = Person.create(first_name: "Graham", surname_id: 8, female: false, parents_id:10, languages_spoken: 1)

@natalie_and_matthew = Parent.create(mother_id: @natalie.id, father_id: @matthew.id, married: true)

@peyton = Person.create(first_name: "Peyton", surname_id: 9, female: true, parents_id:11, languages_spoken: 1)
@tatum = Person.create(first_name: "Tatum", surname_id: 9, female: true, parents_id:11, languages_spoken: 1)


# @rome= @rusty.missions.create(mission_name:"Rome", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
# @pennsylvania = @aaron.missions.create(mission_name: "Pennyslvania", mission_language: "English", country: "United States", members_baptized: 10, foreign_mission: false)
# @oaklahoma = @justin.missions.create(mission_name:"Tulsa", mission_language: "English", country: "United States", members_baptized: 5, foreign_mission: false)
# @brazil = @lee.missions.create(mission_name:"Riberão Preto", mission_language: "Portugese", country: "Brazil", members_baptized: 7, foreign_mission: true)
# @spain = @aaron.missions.create(mission_name:"Madrid", mission_language: "Spanish", country: "Spain", members_baptized: 11, foreign_mission: true)
# @japan = @rayden.missions.create(mission_name: "Tokyo", mission_language: "Japanese", country: "Japan", members_baptized: 3, foreign_mission: true)
# @tennessee = @rylee.missions.create(mission_name: "Tenessee", mission_language: "English", country: "United States", members_baptized: 3, foreign_mission: false)
# @milan= @halee.missions.create(mission_name:"Milan", mission_language: "Italian", country: "Italy", members_baptized: 1, foreign_mission: true)
# @gilbert = @brett.missions.create(mission_name: "Gilbert", mission_language: "English", country: "United States", members_baptized: 0, foreign_mission: false)
# @asuncion = @logan.missions.create(mission_name:"Asuncion", mission_language: "Spanish", country: "Paraguay", members_baptized: 4, foreign_mission: true)
# @puebla = @elaina.missions.create(mission_name:"Puebla", mission_language: "Spanish", country: "Mexico", members_baptized: 4, foreign_mission: true)
# @tijuana = @brian.missions.create(mission_name:"Tijuana", mission_language: "Spanish", country: "Mexico", members_baptized: 4, foreign_mission: true)
# @anchorage = @allen.missions.create(mission_name:"Anchorage", mission_language: "English", country: "United States", members_baptized: 4, foreign_mission: false)
